### ISSUE TITLE
Sequence download causes error

### ISSUE THREAD

**Issue by ejstronge** [lgatto/UniProt.REST#1]
When downloading a protein sequence or isoform list, an error results:

> UniProtProtein('Q5SZL2')
    A Protein retrieved from 'UnitProt.REST'
    Available data for Error in cat(" Available data for ", object@Data[[1]][[1]], ":\n  ", sep = "") : 
    argument 2 (type 'list') cannot be handled by 'cat'

I installed the package using Hadley Wickham's devtools package on a Linux system. Thanks!

**Comment by lgatto** [comment]
The error is in the `show` method, and would be easy to fix. However, I would suggest you consider using another package, for example [`UniProt.ws`](https://bioconductor.org/packages/release/bioc/html/UniProt.ws.html), as this one hasn't been looked after for some time, and should probably be discontinued. What are you trying to do?

**Comment by lgatto** [comment]
I have fixed the `show` method now, but I suggest you use `UniProt.ws` if appropriate - let me know what your needs are, and I will try to help.
